.\" Copyright (C) 2025, David Majnemer <david.majnemer@gmail.com>
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH gate_wait 2 (date) "Linux man-pages (unreleased)"
.SH NAME
gate_wait,
gate_wake
\-
atomic compare-and-block
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.BR "#include <linux/gate.h> " " /* Definition of " "struct gate_*" " */"
.BR "#include <linux/time.h> " " /* Definition of " \
"struct __kernel_timespec" " */"
.BR "#include <linux/types.h>" " /* Definition of " __kernel_* " */"
.BR "#include <sys/syscall.h>" " /* Definition of " SYS_* " constants */"
.BR "#include <sys/types.h>  " " /* Definition of " pid_t " */"
.B #include <unistd.h>
.P
.BI "long syscall(SYS_gate_wait, void *" uaddr ", __kernel_ulong_t " mask ","
.BI "            __kernel_ulong_t " expected ", size_t " usize ","
.BI "            const struct gate_wait_options *" options ","
.BI "            size_t " options_size ");"
.BI "long syscall(SYS_gate_wake, pid_t " pid ", void *" uaddr ","
.BI "            const struct gate_wake_options *" options ","
.BI "            size_t " options_size ");"
.fi
.P
.IR Note :
There are no glibc wrappers for these system calls; they must be invoked directly using
.BR syscall (2).
.SH DESCRIPTION
The
.BR gate_wait ()
and
.BR gate_wake ()
system calls provide a mechanism
for user-space synchronization within a thread group.
They allow a thread to wait efficiently until a specific condition is met
on a memory location,
potentially being woken by another thread in the same process.
These calls offer a simpler, potentially more performant alternative to
.BR futex (2)
for certain use cases by providing a restricted feature set.
.SS gate_wait()
The
.BR gate_wait ()
system call atomically checks a value in user-space memory
and potentially puts the calling thread to sleep if
the value matches an expected state.
.P
The operation proceeds as follows:
.IP (1) 5
Atomically load
.I usize
bytes from the memory address
.IR uaddr .
The address
.I uaddr
must be aligned to
.IR usize .
.IP (2)
Compare
.I *uaddr & mask
with
.IR expected .
.IP (3)
If they are equal,
the calling thread will block.
.IP (4)
If they are unequal,
the system call returns immediately with the error
.BR EAGAIN .
.P
If the thread blocks in step (3), it will remain asleep until one
of the following events occurs:
.IP (a) 5
It is woken by a call to
.BR gate_wake ()
from another thread in
the same thread group, targeting the sleeping thread's TID
.RI ( pid )
and the same memory address
.RI ( uaddr ).
.IP (b)
The wait is interrupted by a signal handler.
.IP (c)
A timeout expires, if one was configured via the
.I options
argument.
.IP (d)
A spurious wakeup occurs (see CAVEATS in
.BR gate (7)).
.P
The
.I options
argument points to a structure that allows for
configuring aspects of the wait.
The
.B gate_wait_options
structure is defined as:
.P
.in +4n
.EX
struct gate_wait_options {
    __u64                     flags;
    struct __kernel_timespec  timeout;
    __s32                     clockid;
    __u32                     __reserved1;
} __attribute__((__aligned__(8)));
.EE
.in
.P
The fields are used as follows:
.TP
.I flags
A bit mask indicating how the structure should be
interpreted.
At most one of the following flags can be
set:
.RS
.TP
.BR GATE_WAIT_ABSTIME " (since Linux 6.14)"
Interpret
.I timeout
as an absolute time point
on the clock specified by
.IR clockid .
.TP
.BR GATE_WAIT_RELTIME " (since Linux 6.14)"
Interpret
.I timeout
as a relative duration from
the current time on the clock specified by
.IR clockid .
.RE
.IP
If neither flag is set,
.I timeout
and
.I clockid
are ignored, and the wait has no timeout.
.TP
.I timeout
Specifies the expiration time.
Ignored if no timeout flag is set in
.IR flags .
.TP
.I clockid
Specifies the clock reference for the timeout.
Must be either
.B CLOCK_MONOTONIC
or
.BR CLOCK_REALTIME .
Ignored if no timeout flag is set in
.IR flags .
See
.BR clock_gettime (2).
.TP
.I __reserved1
Reserved for future use; ignored.
.SS gate_wake()
The
.BR gate_wake ()
system call attempts to wake a specific thread
that is currently blocked in a
.BR gate_wait ()
call.
.P
It targets the thread identified by
.IR pid .
The wakeup attempt is
conditional: it only succeeds if the target thread
.RI ( pid )
is found to be currently blocked inside a
.BR gate_wait ()
system call,
and that call is operating on the exact same memory address
.I uaddr
as provided to
.BR gate_wake ().
.P
The calling thread and the target thread
.I pid
must belong to the same thread group.
.P
The
.B gate_wake_options
structure is defined as:
.P
.in +4n
.EX
struct gate_wake_options {
    __u64 flags;
} __attribute__((__aligned__(8)));
.EE
.in
.P
The fields are used as follows:
.TP
.I flags
Reserved for future use; must be zero.
.SS options_size
The
.I options_size
argument controls how
.I options
is interpreted:
.IP \[bu] 3
If
.I options_size
is zero, then
.I options
is ignored,
and the call behaves as if all fields were present
and set to zero.
.IP \[bu]
If
.I options_size
is nonzero,
.I options
must point to a valid structure, and
.I options_size
should specify its size.
.P
For forward and backward compatibility, the kernel interprets
.I options_size
flexibly:
.IP \[bu] 3
If
.I options_size
is smaller than the kernel's known size of a structure,
the kernel assumes any missing bytes are zero.
.IP \[bu]
If
.I options_size
is larger than the kernel's known size of a structure,
the caller must ensure all extra trailing bytes are zero.
If any extra bytes are nonzero, the call fails with
.BR E2BIG .
.SH RETURN VALUE
On error, \-1 is returned, and
.I errno
is set appropriately to
indicate the cause of the error (see ERRORS).
.SS gate_wait()
On success, 0 is returned.
This indicates the thread met the initial
wait condition
.IR "*uaddr & mask == expected" ,
entered a wait state,
and was subsequently woken up.
The wakeup could be initiated by
a call to
.BR gate_wake ()
or occur spuriously.
.SS gate_wake()
On success,
.BR gate_wake ()
returns one of the following non-negative values:
.TP 5
.B 1
The target thread
.I pid
was found, was blocked in
.BR gate_wait ()
on the specific address
.IR uaddr ,
and was
successfully woken up.
.TP 5
.B 0
The target thread
.I pid
was found, but it was
.B not
currently blocked in a
.BR gate_wait ()
call (on any address)
at the moment
.BR gate_wake ()
performed its check.
.SH ERRORS
Both system calls can fail with the following errors:
.TP
.B E2BIG
The specified
.I options_size
is larger than the structure
size known to the kernel, and the extra trailing bytes
provided by the caller contain nonzero values.
.TP
.B E2BIG
The specified
.I options_size
exceeds a system limit.
.TP
.B EFAULT
.I options
points to an invalid memory
address.
.TP
.B EINVAL
The
.I flags
field in the respective
.I options
structure contained invalid or reserved bits set to 1.
.P
The
.BR gate_wait ()
system call can also fail with the following errors:
.TP
.B EAGAIN
The condition
.I *uaddr & mask == expected
was false when checked atomically.
The thread did not block.
.TP
.B EFAULT
.I uaddr
points to invalid memory.
.TP
.B EINTR
The wait was interrupted by a signal (see
.BR signal (7)).
.TP
.B EINVAL
.I uaddr
was not aligned to
.IR usize .
.TP
.B EINVAL
.I usize
was 0, not a power of two, or larger than
.IR sizeof(__kernel_ulong_t) .
.TP
.B EINVAL
.I options.clockid
was not
.B CLOCK_MONOTONIC
or
.BR CLOCK_REALTIME .
.TP
.B EINVAL
.I options.timeout.tv_sec
was negative, or
.I options.timeout.tv_nsec
was outside the range [0,
999,999,999].
.TP
.B ETIMEDOUT
The wait timed out before being woken
up or interrupted by a signal.
.P
The
.BR gate_wake ()
system call can also fail with the following errors:
.TP
.B EAGAIN
The target thread
.I pid
was found and was blocked in
.BR gate_wait (),
but not on the specified address
.IR uaddr .
.TP
.B EPERM
The calling thread and the target thread
.I pid
do not belong to the same thread group.
.TP
.B ESRCH
No thread with the ID
.I pid
exists (or it terminated).
.SH VERSIONS
These system calls first appeared in Linux 6.14.
.SH STANDARDS
These system calls are Linux-specific.
.SH EXAMPLES
The program below demonstrates the use of gates in a scenario where a parent
process and a child process synchronize access to the terminal using a pair of
gates located in memory.
Both processes write
.I nloops
messages to the terminal and alternate their outputs using a
synchronization protocol.
The following output may be observed upon running the program:
.P
.in +4n
.EX
$ \fB./gate_demo\fP
Parent (18534) 0
Child  (18535) 0
Parent (18534) 1
Child  (18535) 1
Parent (18534) 2
Child  (18535) 2
Parent (18534) 3
Child  (18535) 3
Parent (18534) 4
Child  (18535) 4
.EE
.in
.SS Program source
\&
.\" SRC BEGIN (gate_demo.c)
.EX
/* NOLINTBEGIN(clang-diagnostic-pre-c11-compat) */
/* gate_demo.c
\&
   Usage: gate_demo [nloops=5]
\&
   Demonstrate the use of gates in a program where parent and child
   synchronize access to a shared resource (the terminal) using a pair
   of gates. Each thread writes \[aq]nloops\[aq] messages to the
   terminal, alternating their outputs.
*/
#define _GNU_SOURCE
#include <err.h>         /* for err() */
#include <errno.h>       /* for E* , errno */
#include <linux/gate.h>  /* for GATE_* */
#include <sched.h>       /* for CLONE_* */
#include <stdatomic.h>   /* for atomic_*() */
#include <stdint.h>      /* for uint8_t */
#include <stdio.h>       /* for printf() */
#include <stdlib.h>      /* for strtol(), exit(), EXIT_* */
#include <sys/mman.h>    /* for mmap(), MAP_* */
#include <sys/syscall.h> /* for __NR_gate_* */
#include <time.h>        /* for CLOCK_* */
#include <unistd.h>      /* for syscall(), gettid() */
\&
#define DEFAULT_NLOOPS 5
#define STACK_SIZE (1024 * 1024)
\&
static _Atomic uint8_t child_gate = 0;  /* State: unavailable */
static _Atomic uint8_t parent_gate = 1; /* State: available */
\&
static long            nloops;
\&
static pid_t           parent_tid;
\&
/* Acquire the gate pointed to by \[aq]gatep\[aq]:
   wait until its value becomes 1, then atomically set it to 0. */
\&
static void
gate_wait(_Atomic uint8_t *gatep)
{
    long     s;
    uint8_t desired = 0;
    uint8_t expected;
\&
    /* atomic_compare_exchange_strong(ptr, expected, desired)
       atomically performs the equivalent of:
\&
           old = *ptr;
           if (old == *expected) {
               *ptr = desired;
               return true;
           } else {
               *expected = old;
               return false;
           }
\&
       It returns true if the operation succeeded. */
\&
    while (1) {
        /* Check if the gate is available. */
        expected = 1;
        if (atomic_compare_exchange_strong(gatep, &expected, desired))
            break; /* Gate acquired */
\&
        /* Gate is not available; wait. */
\&
        s = syscall(__NR_gate_wait, gatep, (__kernel_ulong_t) -1,
                    (__kernel_ulong_t) expected, sizeof(*gatep),
                    (const struct gate_wake_options *) NULL,
                    (size_t) 0);
        if (s == -1 && errno != EAGAIN)
            err(EXIT_FAILURE, "gate_wait");
    }
}
\&
/* Release the gate pointed to by \[aq]gatep\[aq]:
   if the gate value is 0, set it to 1 and wake \[aq]pid\[aq]. */
\&
static void
gate_post(pid_t pid, _Atomic uint8_t *gatep)
{
    long    s;
    uint8_t desired = 1;
    uint8_t expected = 0;
\&
    /* atomic_compare_exchange_strong() was described
       in comments above. */
\&
    if (atomic_compare_exchange_strong(gatep, &expected, desired)) {
        s = syscall(__NR_gate_wake, pid, gatep,
                    (const struct gate_wake_options *) NULL,
                    (size_t) 0);
        if (s == -1 && errno != EAGAIN)
            err(EXIT_FAILURE, "gate_wake");
    }
}
\&
static int
child_thread_fn(void *unused)
{
    pid_t  child_tid;
\&
    (void) unused;
    child_tid = gettid();
    for (long j = 0; j < nloops; j++) {
        gate_wait(&child_gate);
        printf("Child  (%jd) %ld\[rs]n", (intmax_t) child_tid, j);
        gate_post(parent_tid, &parent_gate);
    }
\&
    return 0;
}
\&
int
main(int argc, char *argv[])
{
    void  *stack;
    pid_t  child_tid;
\&
    if (argc > 1) {
        nloops = strtol(argv[1], NULL, 0);
        if (errno)
            err(EXIT_FAILURE, "nloops");
    } else {
        nloops = DEFAULT_NLOOPS;
    }
\&
    parent_tid = gettid();
\&
    /* Allocate stack for the child thread. */
\&
    stack = mmap(NULL, STACK_SIZE, PROT_READ | PROT_WRITE,
                 MAP_PRIVATE | MAP_ANONYMOUS | MAP_STACK, \-1, 0);
    if (stack == MAP_FAILED)
        err(EXIT_FAILURE, "mmap stack");
\&
    /* Create a child thread. */
\&
    child_tid =
        clone(child_thread_fn, (char *) stack + STACK_SIZE,
              CLONE_VM | CLONE_SIGHAND | CLONE_THREAD,
              NULL);
    if (child_tid == -1)
        err(EXIT_FAILURE, "clone");
\&
    /* Parent continues execution. */
\&
    for (long j = 0; j < nloops; j++) {
        gate_wait(&parent_gate);
        printf("Parent (%jd) %ld\[rs]n", (intmax_t) parent_tid, j);
        gate_post(child_tid, &child_gate);
    }
\&
    gate_wait(&parent_gate);
\&
    exit(EXIT_SUCCESS);
}
/* NOLINTEND(clang-diagnostic-pre-c11-compat) */
.EE
.\" SRC END
.SH SEE ALSO
.BR futex (2),
.BR gate (7),
.BR signal (7),
.BR syscall (2),
.BR time (7)
.P
.I Documentation/memory\-barriers.txt
